/* eslint-disable @typescript-eslint/no-require-imports -- This Next.js configuration is CommonJS. */
const { createHash } = require('node:crypto');
const { readFileSync } = require('node:fs');
const path = require('node:path');
/* eslint-enable @typescript-eslint/no-require-imports */

const demoAssets = ['worker.js', 'viewer.html', 'sql-wasm.js', 'sql-wasm.wasm'];
// Version the entire set together: cached JS glue cannot use a newer WASM ABI.
// Hash the generated bytes at website build time, not a manually bumped version.
const demoAssetHashes = demoAssets.map(name => [name, createHash('sha256')
  .update(readFileSync(path.join(__dirname, 'public/sqlite-viewer', name)))
  .digest('hex')]);
const demoAssetRevision = createHash('sha256')
  .update(JSON.stringify(demoAssetHashes))
  .digest('hex');
const demoAssetBasePath = `/sqlite-viewer/${demoAssetRevision}`;

/** @type {import('next').NextConfig} */
const nextConfig = {
  // Enable React strict mode for better development experience
  reactStrictMode: true,

  env: {
    NEXT_PUBLIC_SQLITE_VIEWER_BASE_PATH: demoAssetBasePath,
  },

  // Exact rewrites keep relative importScripts/WASM URLs in this revision.
  // Unknown revisions must 404, never silently resolve to different bytes.
  async rewrites() {
    return demoAssets.map(name => ({
      source: `${demoAssetBasePath}/${name}`,
      destination: `/sqlite-viewer/${name}`,
    }));
  },

  // Optimize images from external sources if needed
  images: {
    formats: ['image/avif', 'image/webp'],
  },

  // Headers for security and caching
  async headers() {
    return [
      {
        source: '/:path*',
        headers: [
          {
            key: 'X-DNS-Prefetch-Control',
            value: 'on',
          },
          // X-Frame-Options removed so the demo page can frame its
          // same-origin viewer; frame-ancestors is the framing policy.
          // Only same-origin framing exists (demo -> /sqlite-viewer/viewer.html),
          // on production, previews and localhost alike, so 'self' suffices.
          {
            key: 'Content-Security-Policy',
            value: "frame-ancestors 'self'",
          },
          {
            key: 'X-Content-Type-Options',
            value: 'nosniff',
          },
          {
            key: 'Referrer-Policy',
            value: 'origin-when-cross-origin',
          },
        ],
      },
      ...demoAssets.map(name => ({
        source: `${demoAssetBasePath}/${name}`,
        headers: [{
          key: 'Cache-Control',
          value: 'public, max-age=31536000, immutable',
        }],
      })),
    ];
  },
};

module.exports = nextConfig;
